"""add contract workflow fields

Revision ID: a2b36972b615
Revises: 711b745b7b8f
Create Date: 2026-08-20 17:09:23.049482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b36972b615'
down_revision: Union[str, Sequence[str], None] = '711b745b7b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "contracts",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True
        )
    )

    op.add_column(
        "contracts",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=True
        )
    )

    op.add_column(
        "contracts",
        sa.Column(
            "reviewed_at",
            sa.DateTime(),
            nullable=True
        )
    )

    op.add_column(
        "contracts",
        sa.Column(
            "approved_at",
            sa.DateTime(),
            nullable=True
        )
    )

    # Give existing contracts a timestamp
    op.execute(
        "UPDATE contracts SET created_at = NOW() WHERE created_at IS NULL"
    )

    op.execute(
        "UPDATE contracts SET updated_at = NOW() WHERE updated_at IS NULL"
    )

    # Make timestamps mandatory after existing rows are populated
    op.alter_column(
        "contracts",
        "created_at",
        nullable=False
    )

    op.alter_column(
        "contracts",
        "updated_at",
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'approved_at')
    op.drop_column('contracts', 'reviewed_at')
    op.drop_column('contracts', 'updated_at')
    op.drop_column('contracts', 'created_at')
    # ### end Alembic commands ###
