"""initial ContractIQ schema"""
from alembic import op
import sqlalchemy as sa
revision="0001"; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("users",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("full_name",sa.String(150),nullable=False),sa.Column("email",sa.String(255),nullable=False,unique=True),sa.Column("hashed_password",sa.String(255),nullable=False),sa.Column("role",sa.String(40),nullable=False,server_default="Employee"),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_users_email","users",["email"],unique=True)
    op.create_index("ix_users_role","users",["role"])
    op.create_table("contracts",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("title",sa.String(255),nullable=False),sa.Column("contract_number",sa.String(80),nullable=False,unique=True),sa.Column("category",sa.String(80),nullable=False),sa.Column("description",sa.Text()),sa.Column("start_date",sa.Date(),nullable=False),sa.Column("end_date",sa.Date(),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="Draft"),sa.Column("created_by",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("assigned_to",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("reviewed_at",sa.DateTime(timezone=True)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_contracts_contract_number","contracts",["contract_number"],unique=True); op.create_index("ix_contracts_status","contracts",["status"])
    op.create_table("contract_versions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("contract_id",sa.Integer(),sa.ForeignKey("contracts.id",ondelete="CASCADE"),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("file_path",sa.String(500)),sa.Column("change_summary",sa.Text()),sa.Column("created_by",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("obligations",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("contract_id",sa.Integer(),sa.ForeignKey("contracts.id",ondelete="CASCADE"),nullable=False),sa.Column("title",sa.String(255),nullable=False),sa.Column("description",sa.Text()),sa.Column("obligation_type",sa.String(80),nullable=False),sa.Column("due_date",sa.Date(),nullable=False),sa.Column("assigned_to",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="Pending"),sa.Column("completion_date",sa.Date()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_obligations_due_date","obligations",["due_date"]); op.create_index("ix_obligations_status","obligations",["status"])
    op.create_table("renewals",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("contract_id",sa.Integer(),sa.ForeignKey("contracts.id",ondelete="CASCADE"),nullable=False),sa.Column("renewal_date",sa.Date(),nullable=False),sa.Column("previous_expiry_date",sa.Date(),nullable=False),sa.Column("new_expiry_date",sa.Date()),sa.Column("status",sa.String(30),nullable=False,server_default="Upcoming"),sa.Column("assigned_to",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("notes",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_renewals_status","renewals",["status"])
    op.create_table("notifications",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("contract_id",sa.Integer(),sa.ForeignKey("contracts.id",ondelete="SET NULL")),sa.Column("obligation_id",sa.Integer(),sa.ForeignKey("obligations.id",ondelete="SET NULL")),sa.Column("notification_type",sa.String(50),nullable=False),sa.Column("title",sa.String(255),nullable=False),sa.Column("message",sa.Text(),nullable=False),sa.Column("status",sa.String(20),nullable=False,server_default="Unread"),sa.Column("scheduled_at",sa.DateTime(timezone=True)),sa.Column("sent_at",sa.DateTime(timezone=True)),sa.Column("read_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_notifications_user_id","notifications",["user_id"]); op.create_index("ix_notifications_status","notifications",["status"])
    op.create_table("reports",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("report_type",sa.String(60),nullable=False),sa.Column("title",sa.String(255),nullable=False),sa.Column("generated_by",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("file_path",sa.String(500)),sa.Column("parameters",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("compliance_records",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("contract_id",sa.Integer(),sa.ForeignKey("contracts.id",ondelete="CASCADE"),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("compliance_score",sa.Numeric(5,2),nullable=False),sa.Column("risk_level",sa.String(20),nullable=False),sa.Column("completed_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("pending_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("overdue_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("notes",sa.Text()),sa.Column("evaluated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_compliance_records_contract_id","compliance_records",["contract_id"])
    op.create_table("audit_logs",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("action",sa.String(100),nullable=False),sa.Column("entity_type",sa.String(80),nullable=False),sa.Column("entity_id",sa.Integer()),sa.Column("old_values",sa.JSON()),sa.Column("new_values",sa.JSON()),sa.Column("ip_address",sa.String(45)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("activities",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("activity_type",sa.String(80),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("entity_type",sa.String(80)),sa.Column("entity_id",sa.Integer()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))

def downgrade():
    for t in ["activities","audit_logs","compliance_records","reports","notifications","renewals","obligations","contract_versions","contracts","users"]: op.drop_table(t)
