"""Sprint 12 notifications

Revision ID: 02402fa124f7
Revises: eb05b207e97e
Create Date: 2026-08-31 17:14:17.190164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02402fa124f7'
down_revision: Union[str, Sequence[str], None] = 'eb05b207e97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('obligation_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('notifications', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('notifications', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=False)
    op.drop_constraint(op.f('notifications_contract_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'contracts', ['contract_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notifications', 'obligations', ['obligation_id'], ['id'], ondelete='SET NULL')
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_contract_id_fkey'), 'notifications', 'contracts', ['contract_id'], ['id'])
    op.alter_column('notifications', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'scheduled_at')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'obligation_id')
    # ### end Alembic commands ###
