"""add password column to users

Revision ID: 0354b583d99a
Revises: 9895649bbbbe
Create Date: 2026-08-05 22:01:35.268732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0354b583d99a'
down_revision: Union[str, Sequence[str], None] = '9895649bbbbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'users',
        sa.Column(
            'password',
            sa.String(),
            nullable=False,
            server_default='temp123'
        )
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
