"""create obligations table

Revision ID: 0413c60a2f17
Revises: 9afd24af4555
Create Date: 2026-08-27 20:00:51.612768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0413c60a2f17'
down_revision: Union[str, Sequence[str], None] = '9afd24af4555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('obligation_type', sa.String(length=100), nullable=False))
    op.add_column('obligations', sa.Column('assigned_to', sa.Integer(), nullable=False))
    op.add_column('obligations', sa.Column('completion_date', sa.DateTime(), nullable=True))
    op.alter_column('obligations', 'due_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('obligations', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('obligations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('obligations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'obligations', 'users', ['assigned_to'], ['id'])
    op.drop_column('obligations', 'responsible_party')
    op.drop_column('obligations', 'priority')
    op.drop_column('obligations', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('obligations', sa.Column('priority', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('obligations', sa.Column('responsible_party', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'obligations', type_='foreignkey')
    op.alter_column('obligations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('obligations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('obligations', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('obligations', 'due_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('obligations', 'completion_date')
    op.drop_column('obligations', 'assigned_to')
    op.drop_column('obligations', 'obligation_type')
    # ### end Alembic commands ###
