"""create contracts table

Revision ID: 13d92867ae49
Revises: 
Create Date: 2026-08-16 15:13:57.962957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d92867ae49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_contracts_contract_id'), table_name='contracts')
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.drop_constraint(op.f('fk_contracts_current_version_id'), 'contracts', type_='foreignkey')
    op.drop_constraint(op.f('contracts_owner_id_fkey'), 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'contract_type')
    op.drop_column('contracts', 'current_version_id')
    op.drop_column('contracts', 'contract_value')
    op.drop_column('contracts', 'counterparty_name')
    op.drop_column('contracts', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('contracts', sa.Column('counterparty_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('contracts', sa.Column('contract_value', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('current_version_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('contract_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('contracts_owner_id_fkey'), 'contracts', 'users', ['owner_id'], ['user_id'])
    op.create_foreign_key(op.f('fk_contracts_current_version_id'), 'contracts', 'contract_versions', ['current_version_id'], ['version_id'])
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.create_index(op.f('ix_contracts_contract_id'), 'contracts', ['id'], unique=False)
    op.alter_column('contracts', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
