"""add contract workflow fields

Revision ID: 1d3353d1a881
Revises: 79e85c3f6b6f
Create Date: 2026-08-20 13:08:56.020777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3353d1a881'
down_revision: Union[str, Sequence[str], None] = '79e85c3f6b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contracts', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'contracts', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'approved_at')
    op.drop_column('contracts', 'reviewed_at')
    op.drop_column('contracts', 'assigned_to')
    # ### end Alembic commands ###
