"""add compliance monitoring

Revision ID: 1d5d7fab7dee
Revises: b7ad30704648
Create Date: 2026-09-02 19:05:17.832774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5d7fab7dee'
down_revision: Union[str, Sequence[str], None] = 'b7ad30704648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('COMPLIANT', 'PENDING', 'DELAYED', 'NON_COMPLIANT', 'HIGH_RISK', name='compliancestatusenum', native_enum=False), nullable=False),
    sa.Column('compliance_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevelenum', native_enum=False), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_records_id'), 'compliance_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_records_id'), table_name='compliance_records')
    op.drop_table('compliance_records')
    # ### end Alembic commands ###
