"""create renewals table

Revision ID: 2859455dcdd8
Revises: d6e393e4b9a8
Create Date: 2026-08-31 15:42:55.587917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2859455dcdd8'
down_revision: Union[str, Sequence[str], None] = 'd6e393e4b9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewals', sa.Column('previous_expiry_date', sa.Date(), nullable=False))
    op.add_column('renewals', sa.Column('new_expiry_date', sa.Date(), nullable=True))
    op.add_column('renewals', sa.Column('assigned_to', sa.Integer(), nullable=False))
    op.add_column('renewals', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'renewals', 'users', ['assigned_to'], ['id'])
    op.drop_column('renewals', 'renewal_terms')
    op.drop_column('renewals', 'expiry_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewals', sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('renewals', sa.Column('renewal_terms', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'renewals', type_='foreignkey')
    op.drop_column('renewals', 'notes')
    op.drop_column('renewals', 'assigned_to')
    op.drop_column('renewals', 'new_expiry_date')
    op.drop_column('renewals', 'previous_expiry_date')
    # ### end Alembic commands ###
