"""update contracts table for sprint 7

Revision ID: 29d9a70bf213
Revises: 6d48fbdb8a9e
Create Date: 2026-08-17 17:44:43.583842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d9a70bf213'
down_revision: Union[str, Sequence[str], None] = '6d48fbdb8a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activities_user_id_fkey'), 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('contract_versions_uploaded_by_fkey'), 'contract_versions', type_='foreignkey')
    op.create_foreign_key(None, 'contract_versions', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.add_column('contracts', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('contracts', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('contracts', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('contracts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('contracts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('contracts', 'contract_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contracts', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('contracts', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('contracts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'contracts', ['contract_number'])
    op.drop_constraint(op.f('contracts_created_by_fkey'), 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('contracts', 'vendor_name')
    op.drop_column('contracts', 'contract_value')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('obligations_assigned_to_fkey'), 'obligations', type_='foreignkey')
    op.create_foreign_key(None, 'obligations', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('reports_generated_by_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['generated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_generated_by_fkey'), 'reports', 'users', ['generated_by'], ['id'])
    op.drop_constraint(None, 'obligations', type_='foreignkey')
    op.create_foreign_key(op.f('obligations_assigned_to_fkey'), 'obligations', 'users', ['assigned_to'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.add_column('contracts', sa.Column('contract_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('vendor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key(op.f('contracts_created_by_fkey'), 'contracts', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'contracts', type_='unique')
    op.alter_column('contracts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('contracts', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('contracts', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('contracts', 'contract_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('contracts', 'updated_at')
    op.drop_column('contracts', 'created_at')
    op.drop_column('contracts', 'description')
    op.drop_column('contracts', 'category')
    op.drop_column('contracts', 'title')
    op.drop_constraint(None, 'contract_versions', type_='foreignkey')
    op.create_foreign_key(op.f('contract_versions_uploaded_by_fkey'), 'contract_versions', 'users', ['uploaded_by'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key(op.f('activities_user_id_fkey'), 'activities', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
