"""create renewals table

Revision ID: 29f4de65475d
Revises: 80ce68791905
Create Date: 2026-08-28 19:16:37.767457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29f4de65475d'
down_revision: Union[str, Sequence[str], None] = '80ce68791905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('obligations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('obligations', 'obligation_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('obligations', 'assigned_to',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('obligations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('obligations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('obligations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('obligations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('obligations', 'assigned_to',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('obligations', 'obligation_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('obligations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
