"""update contracts table for sprint 7

Revision ID: 5d0ae804fade
Revises: e1eb39db1b7d
Create Date: 2026-08-14 21:51:46.418278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0ae804fade'
down_revision: Union[str, Sequence[str], None] = 'e1eb39db1b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('contracts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('contracts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'updated_at')
    op.drop_column('contracts', 'created_at')
    op.drop_column('contracts', 'category')
    # ### end Alembic commands ###
