"""update contracts for sprint 7

Revision ID: 5d25202f22d5
Revises: 8391886ad1e5
Create Date: 2026-08-26 15:42:13.321053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d25202f22d5'
down_revision: Union[str, Sequence[str], None] = '8391886ad1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('contracts', sa.Column('created_by', sa.Integer(), nullable=False))
    op.alter_column('contracts', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('contracts', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('contracts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('contracts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('contracts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('contracts_owner_id_fkey'), 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'users', ['created_by'], ['id'])
    op.drop_column('contracts', 'party_name')
    op.drop_column('contracts', 'contract_type')
    op.drop_column('contracts', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('contracts', sa.Column('contract_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('party_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key(op.f('contracts_owner_id_fkey'), 'contracts', 'users', ['owner_id'], ['id'])
    op.alter_column('contracts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('contracts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('contracts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('contracts', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('contracts', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('contracts', 'created_by')
    op.drop_column('contracts', 'category')
    # ### end Alembic commands ###
