"""update notifications table for sprint 12

Revision ID: 7c9e4d82fdee
Revises: 1d5d7fab7dee
Create Date: 2026-09-02 19:30:12.543621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9e4d82fdee'
down_revision: Union[str, Sequence[str], None] = '1d5d7fab7dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('obligation_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('notification_type', sa.Enum('RENEWAL_REMINDER', 'OBLIGATION_DUE', 'OBLIGATION_OVERDUE', 'COMPLIANCE_ALERT', 'CONTRACT_APPROVAL', 'CONTRACT_STATUS', name='notificationtypeenum', native_enum=False), nullable=False))
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('status', sa.Enum('UNREAD', 'READ', name='notificationstatusenum', native_enum=False), nullable=True))
    op.add_column('notifications', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'notifications', 'contracts', ['contract_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'obligations', ['obligation_id'], ['id'])
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'scheduled_at')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'obligation_id')
    op.drop_column('notifications', 'contract_id')
    # ### end Alembic commands ###
