"""create obligations table with string enums

Revision ID: 7d04fef362d5
Revises: 1a6b791ffdcd
Create Date: 2026-08-21 18:53:16.516319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d04fef362d5'
down_revision: Union[str, Sequence[str], None] = '1a6b791ffdcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('title', sa.String(), nullable=False))
    op.add_column('obligations', sa.Column('obligation_type', sa.Enum('PAYMENT', 'DELIVERY', 'REPORTING', 'RENEWAL', 'SLA', 'LEGAL', name='obligationtype', native_enum=False), nullable=False))
    op.add_column('obligations', sa.Column('completion_date', sa.DateTime(), nullable=True))
    op.add_column('obligations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('obligations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('obligations', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('obligations', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('obligations', 'assigned_to',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('obligations', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DELAYED', 'OVERDUE', name='obligationstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('obligations', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DELAYED', 'OVERDUE', name='obligationstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('obligations', 'assigned_to',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('obligations', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('obligations', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('obligations', 'updated_at')
    op.drop_column('obligations', 'created_at')
    op.drop_column('obligations', 'completion_date')
    op.drop_column('obligations', 'obligation_type')
    op.drop_column('obligations', 'title')
    # ### end Alembic commands ###
