"""create obligations table

Revision ID: 80ce68791905
Revises: 989e2186561c
Create Date: 2026-08-19 21:24:37.389698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ce68791905'
down_revision: Union[str, Sequence[str], None] = '989e2186561c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('obligations', sa.Column('obligation_type', sa.String(length=100), nullable=True))
    op.add_column('obligations', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('obligations', sa.Column('completion_date', sa.Date(), nullable=True))
    op.add_column('obligations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('obligations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('obligations', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'obligations', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'obligations', type_='foreignkey')
    op.alter_column('obligations', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('obligations', 'updated_at')
    op.drop_column('obligations', 'created_at')
    op.drop_column('obligations', 'completion_date')
    op.drop_column('obligations', 'assigned_to')
    op.drop_column('obligations', 'obligation_type')
    op.drop_column('obligations', 'title')
    # ### end Alembic commands ###
