"""complete renewals fields

Revision ID: 8847f0c2f3fc
Revises: 29f4de65475d
Create Date: 2026-08-28 19:55:04.787786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8847f0c2f3fc'
down_revision: Union[str, Sequence[str], None] = '29f4de65475d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'renewals',
        sa.Column('previous_expiry_date', sa.Date(), nullable=True)
    )

    op.add_column(
        'renewals',
        sa.Column('new_expiry_date', sa.Date(), nullable=True)
    )

    op.add_column(
        'renewals',
        sa.Column('assigned_to', sa.Integer(), nullable=True)
    )

    op.add_column(
        'renewals',
        sa.Column('notes', sa.String(), nullable=True)
    )

    op.add_column(
        'renewals',
        sa.Column('created_at', sa.DateTime(), nullable=True)
    )

    op.add_column(
        'renewals',
        sa.Column('updated_at', sa.DateTime(), nullable=True)
    )

    op.create_foreign_key(
        None,
        'renewals',
        'users',
        ['assigned_to'],
        ['id']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'renewals', type_='foreignkey')
    op.drop_column('renewals', 'updated_at')
    op.drop_column('renewals', 'created_at')
    op.drop_column('renewals', 'notes')
    op.drop_column('renewals', 'assigned_to')
    op.drop_column('renewals', 'new_expiry_date')
    op.drop_column('renewals', 'previous_expiry_date')
    # ### end Alembic commands ###
