"""add compliance monitoring

Revision ID: 89a7f0e88542
Revises: 82ad8ba139b0
Create Date: 2026-08-28 19:43:38.077521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a7f0e88542'
down_revision: Union[str, Sequence[str], None] = '82ad8ba139b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('compliance_status', sa.String(length=50), nullable=False),
    sa.Column('compliance_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('total_obligations', sa.Integer(), nullable=False),
    sa.Column('completed_obligations', sa.Integer(), nullable=False),
    sa.Column('pending_obligations', sa.Integer(), nullable=False),
    sa.Column('overdue_obligations', sa.Integer(), nullable=False),
    sa.Column('delayed_obligations', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_records_contract_id'), 'compliance_records', ['contract_id'], unique=False)
    op.create_index(op.f('ix_compliance_records_id'), 'compliance_records', ['id'], unique=False)
    op.drop_index(op.f('ix_renewals_contract_id'), table_name='renewals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_renewals_contract_id'), 'renewals', ['contract_id'], unique=False)
    op.drop_index(op.f('ix_compliance_records_id'), table_name='compliance_records')
    op.drop_index(op.f('ix_compliance_records_contract_id'), table_name='compliance_records')
    op.drop_table('compliance_records')
    # ### end Alembic commands ###
