"""add contract workflow fields

Revision ID: 989e2186561c
Revises: c61f10e49911
Create Date: 2026-08-19 10:13:14.325809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989e2186561c'
down_revision: Union[str, Sequence[str], None] = 'c61f10e49911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('contracts', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'approved_at')
    op.drop_column('contracts', 'reviewed_at')
    op.drop_column('contracts', 'assigned_to')
    # ### end Alembic commands ###
