"""add obligation tracking fields

Revision ID: b1705af44707
Revises: 984170d7ad88
Create Date: 2026-08-21 19:29:56.795012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1705af44707'
down_revision: Union[str, Sequence[str], None] = '984170d7ad88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add new columns temporarily as nullable
    op.add_column(
        'obligations',
        sa.Column(
            'obligation_type',
            sa.String(),
            nullable=True
        )
    )

    op.add_column(
        'obligations',
        sa.Column(
            'progress',
            sa.Integer(),
            nullable=True
        )
    )

    op.add_column(
        'obligations',
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )

    op.add_column(
        'obligations',
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )

    # Fill existing rows with default values
    op.execute(
        "UPDATE obligations "
        "SET obligation_type = 'General' "
        "WHERE obligation_type IS NULL"
    )

    op.execute(
        "UPDATE obligations "
        "SET progress = 0 "
        "WHERE progress IS NULL"
    )

    op.execute(
        "UPDATE obligations "
        "SET created_at = CURRENT_TIMESTAMP "
        "WHERE created_at IS NULL"
    )

    op.execute(
        "UPDATE obligations "
        "SET updated_at = CURRENT_TIMESTAMP "
        "WHERE updated_at IS NULL"
    )

    # Make columns NOT NULL after existing rows are populated
    op.alter_column(
        'obligations',
        'obligation_type',
        nullable=False
    )

    op.alter_column(
        'obligations',
        'progress',
        nullable=False
    )

    op.alter_column(
        'obligations',
        'created_at',
        nullable=False
    )

    op.alter_column(
        'obligations',
        'updated_at',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obligations', 'updated_at')
    op.drop_column('obligations', 'created_at')
    op.drop_column('obligations', 'progress')
    op.drop_column('obligations', 'obligation_type')
    # ### end Alembic commands ###
