"""create renewals table

Revision ID: b7ad30704648
Revises: 7d04fef362d5
Create Date: 2026-09-02 18:07:58.406109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ad30704648'
down_revision: Union[str, Sequence[str], None] = '7d04fef362d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewals', sa.Column('previous_expiry_date', sa.Date(), nullable=False))
    op.add_column('renewals', sa.Column('new_expiry_date', sa.Date(), nullable=False))
    op.add_column('renewals', sa.Column('assigned_to', sa.Integer(), nullable=False))
    op.add_column('renewals', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('renewals', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('renewals', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('renewals', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('renewals', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('UPCOMING', 'IN_PROGRESS', 'RENEWED', 'EXPIRED', 'CANCELLED', name='renewalstatus', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('renewals_contract_id_key'), 'renewals', type_='unique')
    op.create_foreign_key(None, 'renewals', 'users', ['assigned_to'], ['id'])
    op.drop_column('renewals', 'reminder_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewals', sa.Column('reminder_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'renewals', type_='foreignkey')
    op.create_unique_constraint(op.f('renewals_contract_id_key'), 'renewals', ['contract_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('renewals', 'status',
               existing_type=sa.Enum('UPCOMING', 'IN_PROGRESS', 'RENEWED', 'EXPIRED', 'CANCELLED', name='renewalstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('renewals', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('renewals', 'updated_at')
    op.drop_column('renewals', 'created_at')
    op.drop_column('renewals', 'notes')
    op.drop_column('renewals', 'assigned_to')
    op.drop_column('renewals', 'new_expiry_date')
    op.drop_column('renewals', 'previous_expiry_date')
    # ### end Alembic commands ###
