"""create contracts table

Revision ID: c61f10e49911
Revises: b62c97d465ad
Create Date: 2026-08-16 10:26:04.029075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61f10e49911'
down_revision: Union[str, Sequence[str], None] = 'b62c97d465ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add new columns as nullable first
    op.add_column(
        "contracts",
        sa.Column("contract_number", sa.String(length=100), nullable=True)
    )

    op.add_column(
        "contracts",
        sa.Column("category", sa.String(length=100), nullable=True)
    )

    op.add_column(
        "contracts",
        sa.Column("description", sa.Text(), nullable=True)
    )

    op.add_column(
        "contracts",
        sa.Column("created_by", sa.Integer(), nullable=True)
    )

    op.add_column(
        "contracts",
        sa.Column("created_at", sa.DateTime(), nullable=True)
    )

    op.add_column(
        "contracts",
        sa.Column("updated_at", sa.DateTime(), nullable=True)
    )

    # Copy existing user_id into created_by
    op.execute(
        "UPDATE contracts SET created_by = user_id"
    )

    # Give existing contracts values for the new fields
    op.execute(
        """
        UPDATE contracts
        SET
            contract_number = 'OLD-CNT-' || id,
            category = 'Service Agreement',
            created_at = CURRENT_TIMESTAMP,
            updated_at = CURRENT_TIMESTAMP
        """
    )

    # Make the new columns required
    op.alter_column(
        "contracts",
        "contract_number",
        nullable=False
    )

    op.alter_column(
        "contracts",
        "category",
        nullable=False
    )

    op.alter_column(
        "contracts",
        "created_by",
        nullable=False
    )

    op.alter_column(
        "contracts",
        "created_at",
        nullable=False
    )

    op.alter_column(
        "contracts",
        "updated_at",
        nullable=False
    )

    # Unique contract number
    op.create_index(
        "ix_contracts_contract_number",
        "contracts",
        ["contract_number"],
        unique=True
    )

    # Replace old user_id foreign key with created_by
    op.drop_constraint(
        "contracts_user_id_fkey",
        "contracts",
        type_="foreignkey"
    )

    op.create_foreign_key(
        "contracts_created_by_fkey",
        "contracts",
        "users",
        ["created_by"],
        ["id"]
    )

    # Remove old column
    op.drop_column("contracts", "user_id")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key(op.f('contracts_user_id_fkey'), 'contracts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.drop_column('contracts', 'updated_at')
    op.drop_column('contracts', 'created_at')
    op.drop_column('contracts', 'created_by')
    op.drop_column('contracts', 'description')
    op.drop_column('contracts', 'category')
    op.drop_column('contracts', 'contract_number')
    # ### end Alembic commands ###
