"""Sprint 9 obligations

Revision ID: cd16da5fa19f
Revises: 4b7c8d1e2f90
Create Date: 2026-08-25 16:02:45.600089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd16da5fa19f'
down_revision: Union[str, Sequence[str], None] = '4b7c8d1e2f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('obligation_type', sa.String(length=100), nullable=False))
    op.add_column('obligations', sa.Column('completion_date', sa.Date(), nullable=True))
    op.add_column('obligations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('obligations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('obligations', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('obligations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('obligations', 'due_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('obligations', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(op.f('obligations_contract_id_fkey'), 'obligations', type_='foreignkey')
    op.create_foreign_key(None, 'obligations', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.drop_column('obligations', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'obligations', type_='foreignkey')
    op.create_foreign_key(op.f('obligations_contract_id_fkey'), 'obligations', 'contracts', ['contract_id'], ['id'])
    op.alter_column('obligations', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('obligations', 'due_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('obligations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('obligations', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('obligations', 'updated_at')
    op.drop_column('obligations', 'created_at')
    op.drop_column('obligations', 'completion_date')
    op.drop_column('obligations', 'obligation_type')
    # ### end Alembic commands ###
