"""add contract workflow fields

Revision ID: cf91f4634671
Revises: 5d0ae804fade
Create Date: 2026-08-21 17:08:22.571809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf91f4634671'
down_revision: Union[str, Sequence[str], None] = '5d0ae804fade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('contracts', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'approved_at')
    op.drop_column('contracts', 'reviewed_at')
    op.drop_column('contracts', 'assigned_to')
    # ### end Alembic commands ###
