"""create renewals table

Revision ID: cfdbb006a94e
Revises: db93ab717332
Create Date: 2026-08-27 19:37:56.742887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdbb006a94e'
down_revision: Union[str, Sequence[str], None] = 'db93ab717332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewals', sa.Column('previous_expiry_date', sa.Date(), nullable=True))
    op.add_column('renewals', sa.Column('new_expiry_date', sa.Date(), nullable=True))
    op.add_column('renewals', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('renewals', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('renewals', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('renewals', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'renewals', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'renewals', type_='foreignkey')
    op.drop_column('renewals', 'updated_at')
    op.drop_column('renewals', 'created_at')
    op.drop_column('renewals', 'notes')
    op.drop_column('renewals', 'assigned_to')
    op.drop_column('renewals', 'new_expiry_date')
    op.drop_column('renewals', 'previous_expiry_date')
    # ### end Alembic commands ###
