"""update notifications for alert management

Revision ID: d1e204d374bf
Revises: 78588cf4b962
Create Date: 2026-08-29 18:40:08.118643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e204d374bf'
down_revision: Union[str, Sequence[str], None] = '78588cf4b962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'notifications',
        sa.Column(
            'obligation_id',
            sa.Integer(),
            nullable=True
        )
    )

    op.add_column(
        'notifications',
        sa.Column(
            'title',
            sa.String(length=200),
            server_default='Notification',
            nullable=False
        )
    )

    op.add_column(
        'notifications',
        sa.Column(
            'status',
            sa.String(length=20),
            server_default='Unread',
            nullable=False
        )
    )

    op.add_column(
        'notifications',
        sa.Column(
            'scheduled_at',
            sa.DateTime(),
            nullable=True
        )
    )

    op.add_column(
        'notifications',
        sa.Column(
            'sent_at',
            sa.DateTime(),
            nullable=True
        )
    )

    op.add_column(
        'notifications',
        sa.Column(
            'read_at',
            sa.DateTime(),
            nullable=True
        )
    )

    op.add_column(
        'notifications',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False
        )
    )

    op.alter_column(
        'notifications',
        'contract_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )

    op.create_foreign_key(
        'fk_notifications_obligation_id',
        'notifications',
        'obligations',
        ['obligation_id'],
        ['id']
    )

    op.drop_column(
        'notifications',
        'is_read'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'scheduled_at')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'obligation_id')
    # ### end Alembic commands ###
