"""create obligations table

Revision ID: d6e393e4b9a8
Revises: cf91f4634671
Create Date: 2026-08-22 22:56:48.076039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e393e4b9a8'
down_revision: Union[str, Sequence[str], None] = 'cf91f4634671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('obligation_type', sa.String(length=100), nullable=False))
    op.add_column('obligations', sa.Column('completion_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obligations', 'completion_date')
    op.drop_column('obligations', 'obligation_type')
    # ### end Alembic commands ###
