"""create contracts table

Revision ID: d9d85682bad7
Revises: ac4462115654
Create Date: 2026-08-16 22:38:33.062496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d85682bad7'
down_revision: Union[str, Sequence[str], None] = 'ac4462115654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('contract_number', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('EMPLOYMENT', 'VENDOR', 'SERVICE', 'LEASE', 'PURCHASE', 'PARTNERSHIP', 'CONFIDENTIALITY', name='contractcategory'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'ACTIVE', 'EXPIRED', 'TERMINATED', name='contractstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=True)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_foreign_key(None, 'activities', 'contracts', ['contract_id'], ['id'])
    op.create_foreign_key(None, 'contract_versions', 'contracts', ['contract_id'], ['id'])
    op.create_foreign_key(None, 'obligations', 'contracts', ['contract_id'], ['id'])
    op.create_foreign_key(None, 'renewals', 'contracts', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'renewals', type_='foreignkey')
    op.drop_constraint(None, 'obligations', type_='foreignkey')
    op.drop_constraint(None, 'contract_versions', type_='foreignkey')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
