"""update obligations for sprint 9

Revision ID: db93ab717332
Revises: 2b68f55d9974
Create Date: 2026-08-20 19:33:34.564570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db93ab717332'
down_revision: Union[str, Sequence[str], None] = '2b68f55d9974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add new columns temporarily as nullable
    op.add_column(
        "obligations",
        sa.Column(
            "obligation_type",
            sa.String(length=100),
            nullable=True
        )
    )

    op.add_column(
        "obligations",
        sa.Column(
            "assigned_to",
            sa.Integer(),
            nullable=True
        )
    )

    op.add_column(
        "obligations",
        sa.Column(
            "completion_date",
            sa.Date(),
            nullable=True
        )
    )

    op.add_column(
        "obligations",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True
        )
    )

    op.add_column(
        "obligations",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True
        )
    )

    # Populate existing obligations
    op.execute("""
        UPDATE obligations
        SET obligation_type = CASE
            WHEN id = 1 THEN 'Reporting'
            WHEN id = 2 THEN 'Security Review'
            WHEN id = 3 THEN 'Vendor Review'
            ELSE 'General'
        END
    """)

    op.execute("""
        UPDATE obligations
        SET assigned_to = 10
        WHERE assigned_to IS NULL
    """)

    # Add foreign key after existing rows have valid assigned_to values
    op.create_foreign_key(
        "fk_obligations_assigned_to_users",
        "obligations",
        "users",
        ["assigned_to"],
        ["id"]
    )

    # Make required columns NOT NULL
    op.alter_column(
        "obligations",
        "obligation_type",
        nullable=False
    )

    op.alter_column(
        "obligations",
        "assigned_to",
        nullable=False
    )

    op.alter_column(
        "obligations",
        "created_at",
        nullable=False
    )

    op.alter_column(
        "obligations",
        "updated_at",
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'obligations', type_='foreignkey')
    op.drop_column('obligations', 'updated_at')
    op.drop_column('obligations', 'created_at')
    op.drop_column('obligations', 'completion_date')
    op.drop_column('obligations', 'assigned_to')
    op.drop_column('obligations', 'obligation_type')
    # ### end Alembic commands ###
