"""create renewals table

Revision ID: e1d78660d15c
Revises: 9c4e3830244e
Create Date: 2026-08-27 12:34:30.586627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1d78660d15c'
down_revision: Union[str, Sequence[str], None] = '9c4e3830244e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'contract_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contracts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('contracts', 'party_name')
    op.alter_column('obligations', 'obligation_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('renewals', sa.Column('previous_expiry_date', sa.Date(), nullable=False))
    op.add_column('renewals', sa.Column('new_expiry_date', sa.Date(), nullable=True))
    op.add_column('renewals', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('renewals', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('renewals', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('renewals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'renewals', 'users', ['assigned_to'], ['id'])
    op.drop_column('renewals', 'renewal_period')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewals', sa.Column('renewal_period', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'renewals', type_='foreignkey')
    op.alter_column('renewals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('renewals', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('renewals', 'updated_at')
    op.drop_column('renewals', 'assigned_to')
    op.drop_column('renewals', 'new_expiry_date')
    op.drop_column('renewals', 'previous_expiry_date')
    op.alter_column('obligations', 'obligation_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('contracts', sa.Column('party_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('contracts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('contracts', 'contract_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
