"""Sprint 10 renewals

Revision ID: eb05b207e97e
Revises: cd16da5fa19f
Create Date: 2026-08-28 00:46:01.551116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb05b207e97e'
down_revision: Union[str, Sequence[str], None] = 'cd16da5fa19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewals', sa.Column('previous_expiry_date', sa.Date(), nullable=False))
    op.add_column('renewals', sa.Column('new_expiry_date', sa.Date(), nullable=False))
    op.add_column('renewals', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('renewals', sa.Column('notes', sa.String(length=500), nullable=True))
    op.add_column('renewals', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('renewals', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('renewals', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('renewals', 'renewal_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('renewals', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(op.f('renewals_contract_id_key'), 'renewals', type_='unique')
    op.drop_constraint(op.f('renewals_contract_id_fkey'), 'renewals', type_='foreignkey')
    op.create_foreign_key(None, 'renewals', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'renewals', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.drop_column('renewals', 'reminder_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewals', sa.Column('reminder_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'renewals', type_='foreignkey')
    op.drop_constraint(None, 'renewals', type_='foreignkey')
    op.create_foreign_key(op.f('renewals_contract_id_fkey'), 'renewals', 'contracts', ['contract_id'], ['id'])
    op.create_unique_constraint(op.f('renewals_contract_id_key'), 'renewals', ['contract_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('renewals', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('renewals', 'renewal_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('renewals', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('renewals', 'updated_at')
    op.drop_column('renewals', 'created_at')
    op.drop_column('renewals', 'notes')
    op.drop_column('renewals', 'assigned_to')
    op.drop_column('renewals', 'new_expiry_date')
    op.drop_column('renewals', 'previous_expiry_date')
    # ### end Alembic commands ###
