"""create notifications table

Revision ID: f1813a06af27
Revises: 2859455dcdd8
Create Date: 2026-08-31 19:07:25.969841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1813a06af27'
down_revision: Union[str, Sequence[str], None] = '2859455dcdd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('obligation_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_foreign_key(None, 'notifications', 'obligations', ['obligation_id'], ['id'])
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'scheduled_at')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'obligation_id')
    # ### end Alembic commands ###
