"""create notifications table

Revision ID: 98adb5e29bca
Revises: 90638d47dc9e
Create Date: 2026-08-31 18:16:59.246605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98adb5e29bca'
down_revision: Union[str, Sequence[str], None] = '90638d47dc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=100), nullable=False))
    op.add_column('notifications', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('notifications', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notifications', 'obligation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_notifications_contract_id'), 'notifications', ['contract_id'], unique=False)
    op.create_index(op.f('ix_notifications_obligation_id'), 'notifications', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_obligation_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_contract_id'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('notifications', 'obligation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notifications', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'notification_type')
    # ### end Alembic commands ###
