"""add contract assignment for sprint 8

Revision ID: ba82f70ed3f1
Revises: 2feb67cc5981
Create Date: 2026-08-21 16:18:03.092496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba82f70ed3f1'
down_revision: Union[str, Sequence[str], None] = '2feb67cc5981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'assigned_to')
    # ### end Alembic commands ###
