"""create notifications table

Revision ID: afd4fa29c6ae
Revises: e056930be7fb
Create Date: 2026-08-31 19:41:25.580928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd4fa29c6ae'
down_revision: Union[str, Sequence[str], None] = 'e056930be7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('title', sa.String(length=200), nullable=False))
    op.add_column('notifications', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('notifications', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('notifications', 'contract_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('notifications', 'subject')
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.alter_column('notifications', 'contract_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'scheduled_at')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###
