"""add contract workflow fields

Revision ID: b00962c5e652
Revises: 03c7b40cf0c5
Create Date: 2026-08-19 18:24:59.727561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00962c5e652'
down_revision: Union[str, Sequence[str], None] = '03c7b40cf0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('assigned_to', sa.BigInteger(), nullable=True))
    op.add_column('contracts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('contracts', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('contracts', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'approved_at')
    op.drop_column('contracts', 'reviewed_at')
    op.drop_column('contracts', 'updated_at')
    op.drop_column('contracts', 'assigned_to')
    # ### end Alembic commands ###

# """add contract workflow fields

# Revision ID: b00962c5e652
# Revises: 03c7b40cf0c5
# Create Date: 2026-08-19 18:24:59.727561

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = 'b00962c5e652'
# down_revision: Union[str, Sequence[str], None] = '03c7b40cf0c5'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     op.add_column(
#         'contracts',
#         sa.Column(
#             'assigned_to',
#             sa.BigInteger(),
#             nullable=True
#         )
#     )

#     op.add_column(
#         'contracts',
#         sa.Column(
#             'updated_at',
#             sa.DateTime(),
#             server_default=sa.text('now()'),
#             nullable=False
#         )
#     )

#     op.add_column(
#         'contracts',
#         sa.Column(
#             'reviewed_at',
#             sa.DateTime(),
#             nullable=True
#         )
#     )

#     op.add_column(
#         'contracts',
#         sa.Column(
#             'approved_at',
#             sa.DateTime(),
#             nullable=True
#         )
#     )

#     op.create_foreign_key(
#         'fk_contracts_assigned_to_users',
#         'contracts',
#         'users',
#         ['assigned_to'],
#         ['id']
#     )


# def downgrade() -> None:
#     """Downgrade schema."""
#     op.drop_constraint(
#         'fk_contracts_assigned_to_users',
#         'contracts',
#         type_='foreignkey'
#     )

#     op.drop_column('contracts', 'approved_at')
#     op.drop_column('contracts', 'reviewed_at')
#     op.drop_column('contracts', 'updated_at')
#     op.drop_column('contracts', 'assigned_to')