"""update renewals table for sprint 10

Revision ID: e056930be7fb
Revises: bbd28c3e17e8
Create Date: 2026-08-30 10:39:05.824768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e056930be7fb'
down_revision: Union[str, Sequence[str], None] = 'bbd28c3e17e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewals', sa.Column('assigned_to', sa.BigInteger(), nullable=False))
    op.add_column('renewals', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('renewals', sa.Column('new_expiry_date', sa.Date(), nullable=True))
    op.add_column('renewals', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('renewals', sa.Column('previous_expiry_date', sa.Date(), nullable=False))
    op.add_column('renewals', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('renewals_managed_by_fkey'), 'renewals', type_='foreignkey')
    op.create_foreign_key(None, 'renewals', 'users', ['assigned_to'], ['id'])
    op.drop_column('renewals', 'remarks')
    op.drop_column('renewals', 'decision')
    op.drop_column('renewals', 'managed_by')
    op.drop_column('renewals', 'new_end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('renewals', sa.Column('new_end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('renewals', sa.Column('managed_by', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('renewals', sa.Column('decision', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('renewals', sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'renewals', type_='foreignkey')
    op.create_foreign_key(op.f('renewals_managed_by_fkey'), 'renewals', 'users', ['managed_by'], ['id'])
    op.drop_column('renewals', 'updated_at')
    op.drop_column('renewals', 'previous_expiry_date')
    op.drop_column('renewals', 'notes')
    op.drop_column('renewals', 'new_expiry_date')
    op.drop_column('renewals', 'status')
    op.drop_column('renewals', 'assigned_to')
    # ### end Alembic commands ###
