from enum import Enum


class UserRole(str, Enum):
    ADMINISTRATOR = "ADMINISTRATOR"
    LEGAL_MANAGER = "LEGAL_MANAGER"
    COMPLIANCE_OFFICER = "COMPLIANCE_OFFICER"
    CONTRACT_MANAGER = "CONTRACT_MANAGER"
    DEPARTMENT_HEAD = "DEPARTMENT_HEAD"
    EMPLOYEE = "EMPLOYEE"