"""add description to contracts

Revision ID: 03c7b40cf0c5
Revises: a1e0b20962f2
Create Date: 2026-08-17 18:16:42.606027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c7b40cf0c5'
down_revision: Union[str, Sequence[str], None] = 'a1e0b20962f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'description')
    # ### end Alembic commands ###
