"""add department to contracts

Revision ID: a02c37388ea4
Revises: afd4fa29c6ae
Create Date: 2026-09-10 19:30:00.738815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02c37388ea4'
down_revision: Union[str, Sequence[str], None] = 'afd4fa29c6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('department', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_contracts_department'), 'contracts', ['department'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_department'), table_name='contracts')
    op.drop_column('contracts', 'department')
    # ### end Alembic commands ###
