"""create obligations table

Revision ID: bbd28c3e17e8
Revises: b00962c5e652
Create Date: 2026-08-20 18:18:09.623386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbd28c3e17e8'
down_revision: Union[str, Sequence[str], None] = 'b00962c5e652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('obligations', sa.Column('obligation_type', sa.String(length=100), nullable=False))
    op.add_column('obligations', sa.Column('completion_date', sa.Date(), nullable=True))
    op.add_column('obligations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('obligations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('obligations', 'priority',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('obligations', 'completed_at')
    op.drop_column('obligations', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('obligations', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('obligations', 'priority',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('obligations', 'updated_at')
    op.drop_column('obligations', 'created_at')
    op.drop_column('obligations', 'completion_date')
    op.drop_column('obligations', 'obligation_type')
    op.drop_column('obligations', 'description')
    # ### end Alembic commands ###
